# Generated by Django 2.2.9 on 2020-01-07 06:41

from django.db import migrations



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
            ],
        ),
    ]
