# Generated by Django 2.2.9 on 2020-01-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casandra_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exampledata',
            fields=[
            ],
        ),
    ]
