# Generated by Django 2.2.9 on 2020-01-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casandra_app', '0002_exampledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='bat',
            fields=[
            ],
        ),
    ]
